name: 使用公开库构建APK

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: '构建类型（debug或release）'
        required: true
        default: 'release'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装系统依赖
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk ccache build-essential libffi-dev libssl-dev wget

      - name: 安装Buildozer和Python依赖
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          pip install kivy==2.3.0 kivymd==1.1.1 openpyxl==3.1.2

      - name: 使用Buildozer构建APK
        id: build-apk-step
        run: |
          buildozer android ${{ github.event.inputs['build-type'] }} || { 
            cat ./.buildozer/android/platform/build/build.log > build_error.log; 
            exit 1; 
          }

      - name: 上传APK制品
        if: steps.build-apk-step.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: worktime_apk
          path: bin/*.apk

      - name: 上传错误日志
        if: steps.build-apk-step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: build_error_logs
          path: build_error.log    
