name: 制作APK

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: '构建类型（debug 或 release）'
        required: true
        default: 'release'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取仓库代码
      uses: actions/checkout@v3

    - name: 安装 Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装系统依赖和 Buildozer
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk ccache build-essential libffi-dev libssl-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: 查看项目目录结构
      run: |
        echo "当前目录结构："
        ls -lR

    - name: 显示 buildozer.spec 内容
      run: |
        cat buildozer.spec || echo "未找到 buildozer.spec"

    - name: 初始化 buildozer
      run: |
        buildozer init || true

    - name: 执行 Buildozer 构建
      run: |
        buildozer android ${{ github.event.inputs.build-type }} || true

    - name: 上传 APK 文件（如果有）
      uses: actions/upload-artifact@v4
      with:
        name: worktime_apk
        path: bin/*.apk

    - name: 上传构建日志（如果存在）
      if: failure() || always()
      uses: actions/upload-artifact@v4
      with:
        name: build_logs
        path: ./.buildozer/android/platform/build/build.log
