name: Build APK Simplified

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: '构建类型（debug 或 release）'
        required: true
        default: 'release'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk ccache build-essential libffi-dev libssl-dev wget

      - name: Install Buildozer and Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK using Buildozer
        run: |
          buildozer android ${{ github.event.inputs['build-type'] }} || { cat ./.buildozer/android/platform/build/build.log; false; }
        continue-on-error: true

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: worktime_apk
          path: bin/*.apk

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: ./.buildozer/android/platform/build/build.log
