- name: 步骤 10/12 - 设置 Android 环境变量
  run: |
    echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
    echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV
    echo "PATH=$PATH:/home/runner/android-sdk/cmdline-tools/latest/bin:/home/runner/android-sdk/platform-tools" >> $GITHUB_ENV
