name: Build Signed APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6

    - name: Configure Buildozer.spec
      run: |
        # 初始化配置文件（如果不存在）
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # 优化配置
        sed -i 's/title = My Application/title = 工时价格Excel生成器/g' buildozer.spec
        sed -i 's/package.name = myapp/package.name = gzexcel/g' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.example/g' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,pandas,openpyxl/g' buildozer.spec
        sed -i 's/source.main = main.py/source.main = gz.py/g' buildozer.spec
        sed -i '/android.permissions =/c\android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' buildozer.spec
        
        # 添加签名配置
        echo "android.keystore = True" >> buildozer.spec
        echo "android.keystore.password = \$ENV{KEYSTORE_PASSWORD}" >> buildozer.spec
        echo "android.keystore.alias = \$ENV{KEY_ALIAS}" >> buildozer.spec
        echo "android.keystore.alias.password = \$ENV{KEY_PASSWORD}" >> buildozer.spec

    - name: Decode Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
        mkdir -p ~/.buildozer/android/platform/
        mv release.keystore ~/.buildozer/android/platform/

    - name: Build Signed APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        export GRADLE_OPTS="-Xmx4g -Xms1g"
        buildozer -v android release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name:工时价格Excel生成器_${{ github.sha }}
        path: bin/*-release.apk
