name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: '构建类型'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: 步骤 1/10 - 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 步骤 2/10 - 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 步骤 3/10 - 缓存依赖
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: 步骤 4/10 - 安装 Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: 步骤 5/10 - 设置 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 步骤 6/10 - 安装 Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6

    - name: 步骤 7/10 - 安装必要的 Android 构建工具
      run: |
        # 安装最新的 build-tools 和平台
        echo "安装 build-tools 和平台..."
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
        
        # 接受所有许可证
        echo "接受 Android SDK 许可证..."
        yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: 步骤 8/10 - 配置 Buildozer 环境变量
      run: |
        # 创建 Buildozer 配置目录
        mkdir -p ~/.buildozer/android
        
        # 创建 local.properties 文件指定 SDK 路径
        echo "sdk.dir=/home/runner/android-sdk" > ~/.buildozer/android/local.properties
        
        # 打印配置信息用于调试
        echo "Buildozer 配置文件内容:"
        cat ~/.buildozer/android/local.properties

    - name: 步骤 9/10 - 配置 Buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # 基础配置
        sed -i 's/title = My Application/title = 工时价格Excel生成器/g' buildozer.spec
        sed -i 's/package.name = myapp/package.name = gzexcel/g' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.example/g' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,pandas,openpyxl/g' buildozer.spec
        sed -i 's/source.main = main.py/source.main = gz.py/g' buildozer.spec
        
        # 根据构建类型调整配置
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "配置发布版本构建..."
          sed -i '/android.permissions =/c\android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' buildozer.spec
          echo "android.keystore = True" >> buildozer.spec
          echo "android.keystore.password = \$ENV{KEYSTORE_PASSWORD}" >> buildozer.spec
          echo "android.keystore.alias = \$ENV{KEY_ALIAS}" >> buildozer.spec
          echo "android.keystore.alias.password = \$ENV{KEY_PASSWORD}" >> buildozer.spec
        else
          echo "配置调试版本构建..."
        fi

    - name: 步骤 10/10 - 构建 APK
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ANDROID_SDK_ROOT: /home/runner/android-sdk  # 明确设置 SDK 路径
      run: |
        # 打印环境变量和目录结构用于调试
        echo "===== 环境变量 ====="
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "PATH: $PATH"
        
        echo "===== SDK 目录结构 ====="
        echo "SDK 根目录内容:"
        ls -la $ANDROID_SDK_ROOT
        
        echo "build-tools 目录内容:"
        ls -la $ANDROID_SDK_ROOT/build-tools
        
        echo "build-tools 版本列表:"
        ls -la $ANDROID_SDK_ROOT/build-tools
        
        # 准备签名密钥（仅发布版本需要）
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "准备签名密钥..."
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
          mkdir -p ~/.buildozer/android/platform/
          mv release.keystore ~/.buildozer/android/platform/
        fi
        
        # 设置内存限制
        export GRADLE_OPTS="-Xmx4g -Xms1g"
        
        # 执行构建
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "开始构建签名 APK..."
          buildozer -v android release
        else
          echo "开始构建调试 APK..."
          buildozer -v android debug
        fi

    - name: 输出构建结果
      id: output
      run: |
        APK_PATH=$(find bin -name "*-${{ github.event.inputs.release_type }}.apk" | head -1)
        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        
        VERSION=$(grep "version = " buildozer.spec | cut -d'=' -f2 | tr -d ' ')
        echo "VERSION=${VERSION:-unknown}" >> $GITHUB_ENV
        
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

    - name: 上传 APK 构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 工时价格Excel生成器_v${{ env.VERSION }}_${{ github.sha }}
        path: ${{ env.APK_PATH }}
        retention-days: 30

    - name: 构建完成摘要
      run: |
        echo "========================================"
        echo " 构建完成!"
        echo "----------------------------------------"
        echo " 构建类型: ${{ github.event.inputs.release_type }}"
        echo " 版本号: v${{ env.VERSION }}"
        echo " 提交哈希: ${{ github.sha }}"
        echo " 提交信息: ${{ env.COMMIT_MSG }}"
        echo " APK 路径: ${{ env.APK_PATH }}"
        echo "========================================"
