name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: '构建类型'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: 步骤 1/9 - 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 步骤 2/9 - 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 步骤 3/9 - 缓存依赖
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: 步骤 4/9 - 安装 Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: 步骤 5/9 - 设置 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 步骤 6/9 - 安装 Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6

    - name: 步骤 7/9 - 安装必要的 Android 构建工具
      run: |
        # 列出可用的 build-tools 版本
        echo "可用的 build-tools 版本:"
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --list | grep build-tools
        
        # 安装最新的 build-tools（根据实际情况选择版本）
        echo "安装 build-tools..."
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"
        
        # 安装其他必要的组件
        echo "安装其他必要的 Android 组件..."
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "ndk;25.2.9519653"
        
        # 接受所有许可证
        echo "接受 Android SDK 许可证..."
        yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: 步骤 8/9 - 配置 Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        sed -i 's/title = My Application/title = 工时价格Excel生成器/g' buildozer.spec
        sed -i 's/package.name = myapp/package.name = gzexcel/g' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.example/g' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,pandas,openpyxl/g' buildozer.spec
        sed -i 's/source.main = main.py/source.main = gz.py/g' buildozer.spec
        
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "配置发布版本构建..."
          sed -i '/android.permissions =/c\android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' buildozer.spec
          echo "android.keystore = True" >> buildozer.spec
          echo "android.keystore.password = \$ENV{KEYSTORE_PASSWORD}" >> buildozer.spec
          echo "android.keystore.alias = \$ENV{KEY_ALIAS}" >> buildozer.spec
          echo "android.keystore.alias.password = \$ENV{KEY_PASSWORD}" >> buildozer.spec
        else
          echo "配置调试版本构建..."
        fi

    - name: 步骤 9/9 - 构建 APK
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ANDROID_SDK_ROOT: /home/runner/android-sdk  # 明确设置 ANDROID_SDK_ROOT
      run: |
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "准备签名密钥..."
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
          mkdir -p ~/.buildozer/android/platform/
          mv release.keystore ~/.buildozer/android/platform/
        fi
        
        export GRADLE_OPTS="-Xmx4g -Xms1g"
        
        # 打印 Android SDK 路径和内容，用于调试
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "build-tools 目录内容:"
        ls -la $ANDROID_SDK_ROOT/build-tools
        
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "开始构建签名 APK..."
          buildozer -v android release
        else
          echo "开始构建调试 APK..."
          buildozer -v android debug
        fi

    - name: 输出构建结果
      id: output
      run: |
        APK_PATH=$(find bin -name "*-${{ github.event.inputs.release_type }}.apk" | head -1)
        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        
        VERSION=$(grep "version = " buildozer.spec | cut -d'=' -f2 | tr -d ' ')
        echo "VERSION=${VERSION:-unknown}" >> $GITHUB_ENV
        
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

    - name: 上传 APK 构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 工时价格Excel生成器_v${{ env.VERSION }}_${{ github.sha }}
        path: ${{ env.APK_PATH }}
        retention-days: 30

    - name: 构建完成摘要
      run: |
        echo "========================================"
        echo " 构建完成!"
        echo "----------------------------------------"
        echo " 构建类型: ${{ github.event.inputs.release_type }}"
        echo " 版本号: v${{ env.VERSION }}"
        echo " 提交哈希: ${{ github.sha }}"
        echo " 提交信息: ${{ env.COMMIT_MSG }}"
        echo " APK 路径: ${{ env.APK_PATH }}"
        echo "========================================"
