name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: '构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      ANDROID_HOME: /home/runner/android-sdk
      ANDROID_SDK_ROOT: /home/runner/android-sdk
      ANDROID_NDK_HOME: /home/runner/android-sdk/ndk/25.1.8937393
      GRADLE_OPTS: "-Xmx6g -Xms2g"
      PYTHON_VERSION: '3.9'
      ERROR_LOG_PATH: ./build_error.log
      BUILDOZER_VERBOSE: 1  # 启用Buildozer详细输出

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装系统依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          automake libtool autoconf pkg-config build-essential \
          libopenblas-dev liblapack-dev gfortran \
          libssl-dev libffi-dev
        dpkg -l | grep -E 'automake|libtool|autoconf|pkg-config|build-essential' > ${{ env.ERROR_LOG_PATH }} 2>&1

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 清理旧缓存
      run: |
        rm -rf ~/.buildozer ~/.cache/pip .buildozer
      continue-on-error: true

    - name: 安装 Buildozer（验证版本）
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython
        echo "===== 工具版本 =====" >> ${{ env.ERROR_LOG_PATH }}
        pip list | grep -E 'buildozer|cython|pythonforandroid' >> ${{ env.ERROR_LOG_PATH }} 2>&1
        buildozer --version >> ${{ env.ERROR_LOG_PATH }} 2>&1

    - name: 创建必要目录并设置权限
      run: |
        mkdir -p /home/runner/work/android-gsjs/android-gsjs/.buildozer/android/app
        mkdir -p ~/.buildozer/android/platform/
        chmod -R 777 /home/runner/work/android-gsjs/android-gsjs/.buildozer
        echo "===== 目录验证 =====" >> ${{ env.ERROR_LOG_PATH }}
        ls -laR /home/runner/work/android-gsjs/android-gsjs/.buildozer/ >> ${{ env.ERROR_LOG_PATH }} 2>&1

    - name: 设置 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 安装 Android SDK 和 NDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6
      with:
        ndk: '25.1.8937393'

    - name: 验证 Android 工具链
      run: |
        echo "===== Android 工具链 =====" >> ${{ env.ERROR_LOG_PATH }}
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list 2>&1 | grep -E 'build-tools|platforms|ndk' >> ${{ env.ERROR_LOG_PATH }}
        echo "NDK 路径: $ANDROID_NDK_HOME" >> ${{ env.ERROR_LOG_PATH }}
        test -d $ANDROID_NDK_HOME && echo "NDK 目录存在" || echo "NDK 目录不存在" >> ${{ env.ERROR_LOG_PATH }}

    - name: 安装 Android 构建工具
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: 配置 Buildozer 路径
      run: |
        mkdir -p ~/.buildozer/android/platform/
        ln -s $ANDROID_HOME ~/.buildozer/android/platform/android-sdk
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin/
        ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        echo "===== Buildozer 配置 =====" >> ${{ env.ERROR_LOG_PATH }}
        ls -la ~/.buildozer/android/platform/ >> ${{ env.ERROR_LOG_PATH }} 2>&1

    - name: 配置项目规格（确保所有必需参数设置）
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # 设置必需参数
        sed -i -e 's/title = My Application/title = 工时价格Excel生成器/' \
               -e 's/package.name = myapp/package.name = gzexcel/' \
               -e 's/package.domain = org.test/package.domain = com.example/' \
               -e 's/source.main = main.py/source.main = gz.py/' \
               -e 's/version = 1.0/version = 1.0.0/' \  # 确保版本号设置
               buildozer.spec
        
        # 添加缺失的必需配置
        echo "requirements = python3,kivy==2.1.0,kivymd==0.104.2,pandas==1.5.3,openpyxl==3.1.2,numpy==1.24.3" >> buildozer.spec
        echo "android.build_tools_version = 33.0.2" >> buildozer.spec
        echo "android.ndk_version = 25.1.8937393" >> buildozer.spec
        echo "android.archs = arm64-v8a,armeabi-v7a" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec  # 确保源目录设置
        
        # 签名配置（发布版）
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          sed -i '/android.permissions =/c\android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' buildozer.spec
          echo "android.keystore = True" >> buildozer.spec
          echo "android.keystore.password = \$ENV{KEYSTORE_PASSWORD}" >> buildozer.spec
          echo "android.keystore.alias = \$ENV{KEY_ALIAS}" >> buildozer.spec
          echo "android.keystore.alias.password = \$ENV{KEY_PASSWORD}" >> buildozer.spec
        fi
        
        # 验证配置完整性
        echo "===== buildozer.spec =====" >> ${{ env.ERROR_LOG_PATH }}
        cat buildozer.spec >> ${{ env.ERROR_LOG_PATH }} 2>&1
        
        # 检查是否包含必需字段
        echo "===== 配置验证 =====" >> ${{ env.ERROR_LOG_PATH }}
        grep -E '^title|^package\.name|^package\.domain|^source\.main|^version' buildozer.spec >> ${{ env.ERROR_LOG_PATH }} 2>&1

    - name: 构建 APK（最终修复）
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        touch ${{ env.ERROR_LOG_PATH }}
        
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore 2>> ${{ env.ERROR_LOG_PATH }}
          mkdir -p ~/.buildozer/android/platform/ 2>> ${{ env.ERROR_LOG_PATH }}
          mv release.keystore ~/.buildozer/android/platform/ 2>> ${{ env.ERROR_LOG_PATH }}
        fi
        
        echo "===== 开始构建 =====" >> ${{ env.ERROR_LOG_PATH }}
        # 确保命令格式正确：buildozer [全局选项] <目标> <命令> [命令选项]
        buildozer --verbose android ${{ github.event.inputs.release_type }} --log_level=2 2>&1 | tee -a ${{ env.ERROR_LOG_PATH }} || (
          echo "===== 构建失败 =====" >> ${{ env.ERROR_LOG_PATH }}
          if [ -d ".buildozer" ]; then
            echo "===== Buildozer 临时文件 =====" >> ${{ env.ERROR_LOG_PATH }}
            find .buildozer -type f -exec ls -la {} \; >> ${{ env.ERROR_LOG_PATH }} 2>&1
          fi
          exit 1
        )

    - name: 收集额外错误信息（构建失败时）
      if: failure()
      run: |
        echo "===== 环境变量 =====" >> ${{ env.ERROR_LOG_PATH }}
        env >> ${{ env.ERROR_LOG_PATH }}
        echo "===== 系统信息 =====" >> ${{ env.ERROR_LOG_PATH }}
        uname -a >> ${{ env.ERROR_LOG_PATH }}
        java -version 2>> ${{ env.ERROR_LOG_PATH }}
        python --version >> ${{ env.ERROR_LOG_PATH }}
        buildozer --version >> ${{ env.ERROR_LOG_PATH }}

    - name: 上传错误日志和产物
      uses: actions/upload-artifact@v4
      with:
        name: 构建产物与日志_${{ github.sha }}
        path: |
          ${{ env.ERROR_LOG_PATH }}
          bin/*-${{ github.event.inputs.release_type }}.apk
          buildozer.spec
          .buildozer/
        retention-days: 30
