name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: '构建类型'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      ANDROID_HOME: /home/runner/android-sdk
      ANDROID_SDK_ROOT: /home/runner/android-sdk
      ANDROID_NDK_HOME: /home/runner/android-sdk/ndk/25.1.8937393
      GRADLE_OPTS: "-Xmx6g -Xms2g"
      PYTHON_VERSION: '3.9'

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装系统依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          automake libtool autoconf pkg-config build-essential \
          libopenblas-dev liblapack-dev gfortran \
          libssl-dev libffi-dev

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 清理并缓存依赖
      run: |
        rm -rf ~/.buildozer ~/.cache/pip .buildozer
      continue-on-error: true

    - name: 安装 Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython

    - name: 设置 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 安装 Android SDK 和 NDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6
      with:
        ndk: '25.1.8937393'

    - name: 安装 Android 构建工具
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: 配置 Buildozer 路径
      run: |
        mkdir -p ~/.buildozer/android/platform/
        ln -s $ANDROID_HOME ~/.buildozer/android/platform/android-sdk
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin/
        ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: 配置项目规格
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # 使用 sed 批量修改配置
        sed -i -e 's/title = My Application/title = 工时价格Excel生成器/' \
               -e 's/package.name = myapp/package.name = gzexcel/' \
               -e 's/package.domain = org.test/package.domain = com.example/' \
               -e 's/source.main = main.py/source.main = gz.py/' \
               buildozer.spec
        
        # 设置依赖（使用兼容的稳定版本）
        echo "requirements = python3,kivy==2.1.0,kivymd==0.104.2,pandas==1.5.3,openpyxl==3.1.2,numpy==1.24.3" >> buildozer.spec
        
        # Android 构建配置
        echo "android.build_tools_version = 33.0.2" >> buildozer.spec
        echo "android.ndk_version = 25.1.8937393" >> buildozer.spec
        
        # 签名配置（发布版）
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          sed -i '/android.permissions =/c\android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' buildozer.spec
          echo "android.keystore = True" >> buildozer.spec
          echo "android.keystore.password = \$ENV{KEYSTORE_PASSWORD}" >> buildozer.spec
          echo "android.keystore.alias = \$ENV{KEY_ALIAS}" >> buildozer.spec
          echo "android.keystore.alias.password = \$ENV{KEY_PASSWORD}" >> buildozer.spec
        fi

    - name: 构建 APK
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        # 准备签名密钥（发布版）
        if [ "${{ github.event.inputs.release_type }}" == "release" ]; then
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
          mkdir -p ~/.buildozer/android/platform/
          mv release.keystore ~/.buildozer/android/platform/
        fi
        
        # 执行构建（仅在失败时显示完整日志）
        buildozer -v android ${{ github.event.inputs.release_type }} --log_level=2 || (
          echo "构建失败，查看完整日志："
          find .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/logs/ -type f -exec cat {} \;
          exit 1
        )

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 工时价格Excel生成器_${{ github.sha }}
        path: |
          bin/*-${{ github.event.inputs.release_type }}.apk
          buildozer.spec
        retention-days: 30
