name: '使用 Buildozer 构建 Android APK'

on:
  workflow_dispatch:  # 添加手动触发按钮

description: '使用 Buildozer 将 android-gs 项目打包成 APK 文件'

inputs:
  python-version:
    description: '使用的 Python 版本'
    default: '3.8'
  work-dir:
    description: '工作目录'
    default: '.'
  buildozer-cmd:
    description: 'Buildozer 构建命令'
    default: 'buildozer android debug'

branding:
  color: 'green'
  icon: 'play'

runs:
  using: "composite"
  steps:
    - name: 检出代码仓库
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: ${{ inputs.python-version }}

    - name: 安装 Java 17（Gradle 构建需要）
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 配置 JAVA_HOME 环境变量
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
      shell: bash

    - name: 切换到工作目录
      run: |
        cd ${{ inputs.work-dir }}
      shell: bash

    - name: 创建并激活虚拟环境
      run: |
        rm -rf venv
        python3 -m venv venv
        source venv/bin/activate
        echo "当前 Python 版本为: $(python --version)"
      shell: bash

    - name: 安装系统依赖和 Buildozer
      run: |
        source venv/bin/activate
        sudo apt update
        sudo apt install -y git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        export PATH=$PATH:~/.local/bin/
        python3 -m pip install --upgrade \
          Cython==0.29.33 \
          buildo
